/**
 * Copies the repository's Markdown into the Starlight content collection.
 *
 * Output (gitignored, regenerated on every run):
 *   site/src/content/docs/docs/**   except the hand-authored architecture/ page
 *   site/public/assets/**           images referenced by synced pages + architecture diagrams
 *
 * Run with `bun run sync` from site/. Exits non-zero when a source is missing.
 */
import { readdir, rm, stat } from 'node:fs/promises';
import { join, posix, resolve } from 'node:path';

const REPO_URL = 'https://github.com/isac322/flareway';
const SITE_DIR = resolve(import.meta.dir, '..');
const REPO_DIR = resolve(SITE_DIR, '..');
const CONTENT_DIR = join(SITE_DIR, 'src/content/docs/docs');
const ASSETS_OUT_DIR = join(SITE_DIR, 'public/assets');
/** Committed, hand-authored entry inside CONTENT_DIR that the sync must never touch. */
const COMMITTED_ENTRY = 'architecture';
/**
 * Asset globs (relative to repo assets/) copied unconditionally because the
 * committed architecture page embeds them.
 */
const ALWAYS_COPIED_ASSETS = ['architecture/*.svg'];
const DESCRIPTION_MAX = 155;

interface Page {
	/** Repo-relative source path. */
	source: string;
	/** Output path relative to CONTENT_DIR. */
	target: string;
	/** Sidebar position inside the page's autogenerated group. */
	order: number;
	/** Short sidebar label; defaults to the page title. */
	label?: string;
	/** Lines to drop before processing (e.g. the README logo). */
	drop?: RegExp;
}

const PAGES: Page[] = [
	{ source: 'README.md', target: 'index.md', order: 0, drop: /^!\[[^\]]*\]\(assets\/cloud-gateway\/d2\/logo-t3\.svg\)\s*$/ },
	{ source: 'docs/operations/install.md', target: 'operations/install.md', order: 1, label: 'Install' },
	{ source: 'docs/operations/upgrade.md', target: 'operations/upgrade.md', order: 2, label: 'Upgrade' },
	{ source: 'docs/operations/rbac-token.md', target: 'operations/rbac-token.md', order: 3, label: 'RBAC and API tokens' },
	{ source: 'docs/operations/troubleshooting.md', target: 'operations/troubleshooting.md', order: 4, label: 'Troubleshooting' },
	{
		source: 'docs/operations/freshness-and-drift.md',
		target: 'operations/freshness-and-drift.md',
		order: 5,
		label: 'Freshness and drift',
	},
	{ source: 'docs/api-reference.md', target: 'reference/api.md', order: 1, label: 'API reference' },
	{ source: 'docs/api/README.md', target: 'reference/kubectl-explain.md', order: 2, label: 'kubectl explain guide' },
	{
		source: 'conformance/reports/v1.6.2/flareway/README.md',
		target: 'conformance/gateway-api-v1-6-2.md',
		order: 0,
	},
	{ source: 'CONTRIBUTING.md', target: 'project/contributing.md', order: 1, label: 'Contributing' },
	{ source: 'SECURITY.md', target: 'project/security.md', order: 2, label: 'Security policy' },
];

/** `operations/install.md` -> `/docs/operations/install/`, `index.md` -> `/docs/`. */
const routeFor = (target: string) => `/docs/${target.replace(/(^|\/)index\.md$/, '$1').replace(/\.md$/, '/')}`;

/** Repo-relative source path -> site route, for rewriting links between synced pages. */
const ROUTE_BY_SOURCE = new Map(PAGES.map((page) => [page.source, routeFor(page.target)]));
/** Additional committed pages that repo links may point at. */
ROUTE_BY_SOURCE.set('site/src/content/docs/docs/architecture/index.md', '/docs/architecture/');

const copiedAssets = new Set<string>();
const unmapped: string[] = [];

async function pathKind(repoPath: string): Promise<'file' | 'dir' | undefined> {
	try {
		return (await stat(join(REPO_DIR, repoPath))).isDirectory() ? 'dir' : 'file';
	} catch {
		return undefined;
	}
}

async function copyAsset(repoPath: string): Promise<string> {
	const sub = repoPath.slice('assets/'.length);
	if (!copiedAssets.has(sub)) {
		const file = Bun.file(join(REPO_DIR, repoPath));
		if (!(await file.exists())) throw new Error(`referenced asset is missing: ${repoPath}`);
		await Bun.write(join(ASSETS_OUT_DIR, sub), file);
		copiedAssets.add(sub);
	}
	return `/assets/${sub}`;
}

/**
 * Rewrite one link target found in `source`.
 * - another synced page -> its site route (anchor preserved)
 * - image under assets/ -> copied into public/assets/, served from /assets/
 * - any other repo path -> GitHub blob (file) or tree (directory) URL
 * External URLs, in-page anchors, and absolute paths are left alone.
 */
async function rewriteTarget(source: string, target: string, isImage: boolean): Promise<string> {
	if (/^[a-z][a-z0-9+.-]*:/i.test(target) || target.startsWith('#') || target.startsWith('/')) return target;
	const hashAt = target.indexOf('#');
	const pathPart = hashAt === -1 ? target : target.slice(0, hashAt);
	const anchor = hashAt === -1 ? '' : target.slice(hashAt);
	const repoPath = posix.normalize(posix.join(posix.dirname(source), decodeURI(pathPart)));
	if (repoPath.startsWith('../')) {
		unmapped.push(`${source}: ${target} (points outside the repository; left unchanged)`);
		return target;
	}
	const cleanPath = repoPath.replace(/\/$/, '');

	const route = ROUTE_BY_SOURCE.get(cleanPath);
	if (route) return route + anchor;
	if (isImage && cleanPath.startsWith('assets/')) return (await copyAsset(cleanPath)) + anchor;

	const kind = await pathKind(cleanPath);
	if (!kind) unmapped.push(`${source}: ${target} (no such repository path; linked to GitHub anyway)`);
	const view = kind === 'dir' || pathPart.endsWith('/') ? 'tree' : 'blob';
	const suffix = isImage && view === 'blob' ? '?raw=true' : '';
	return `${REPO_URL}/${view}/main/${encodeURI(cleanPath)}${suffix}${anchor}`;
}

async function replaceAsync(
	text: string,
	pattern: RegExp,
	replacer: (...match: string[]) => Promise<string>,
): Promise<string> {
	const replacements = await Promise.all(Array.from(text.matchAll(pattern), (match) => replacer(...match)));
	let index = 0;
	return text.replace(pattern, () => replacements[index++] ?? '');
}

const MD_LINK = /(!?)\[((?:[^[\]]|\[[^\]]*\])*)\]\(\s*(<[^>]+>|[^)\s]+)(\s+"[^"]*")?\s*\)/g;
const MD_REF_DEF = /^( {0,3}\[[^\]]+\]:\s*)(<[^>]+>|\S+)/;
const HTML_ATTR = /(<(img|source|a)\b[^>]*?\s)(src|srcset|href)=("[^"]*"|'[^']*')/gi;

async function rewriteLine(source: string, line: string): Promise<string> {
	let out = await replaceAsync(line, MD_LINK, async (_all, bang = '', text = '', rawTarget = '', title = '') => {
		const target = rawTarget.replace(/^<|>$/g, '');
		return `${bang}[${text}](${await rewriteTarget(source, target, bang === '!')}${title})`;
	});
	const refDef = out.match(MD_REF_DEF);
	if (refDef?.[1] && refDef[2]) {
		const target = refDef[2].replace(/^<|>$/g, '');
		out = refDef[1] + (await rewriteTarget(source, target, false)) + out.slice(refDef[0].length);
	}
	out = await replaceAsync(out, HTML_ATTR, async (_all, prefix = '', tag = '', attr = '', quoted = '') => {
		const quote = quoted[0];
		const value = quoted.slice(1, -1);
		const isImage = tag.toLowerCase() !== 'a';
		const rewritten =
			attr.toLowerCase() === 'srcset'
				? (
						await Promise.all(
							value.split(',').map(async (candidate) => {
								const [url = '', ...descriptor] = candidate.trim().split(/\s+/);
								return [await rewriteTarget(source, url, true), ...descriptor].join(' ');
							}),
						)
					).join(', ')
				: await rewriteTarget(source, value, isImage);
		return `${prefix}${attr}=${quote}${rewritten}${quote}`;
	});
	return out;
}

/** Plain-text rendering of a Markdown paragraph for the description field. */
function plainText(markdown: string): string {
	return markdown
		.replace(/!\[[^\]]*\]\([^)]*\)/g, '')
		.replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
		.replace(/<[^>]+>/g, '')
		.replace(/[`*_]/g, '')
		.replace(/\s+/g, ' ')
		.trim();
}

function truncate(text: string): string {
	if (text.length <= DESCRIPTION_MAX) return text;
	const cut = text.slice(0, DESCRIPTION_MAX - 1);
	const lastSpace = cut.lastIndexOf(' ');
	return `${(lastSpace > 0 ? cut.slice(0, lastSpace) : cut).replace(/[\s,;:.—-]+$/, '')}…`;
}

async function convert(page: Page): Promise<string> {
	const raw = (await Bun.file(join(REPO_DIR, page.source)).text()).replace(/\r\n?/g, '\n');
	const lines = raw.split('\n');

	let title: string | undefined;
	let description: string | undefined;
	let paragraph: string[] = [];
	/** True while inside a block (list, quote, table, HTML, ...) that is not a plain paragraph. */
	let otherBlock = false;
	let fence: string | undefined;
	const body: string[] = [];

	const closeParagraph = () => {
		if (!description && paragraph.length > 0) {
			const text = plainText(paragraph.join(' '));
			if (text) description = truncate(text);
		}
		paragraph = [];
	};

	for (const line of lines) {
		const fenceMatch = line.match(/^\s{0,3}(`{3,}|~{3,})/);
		if (fence) {
			if (fenceMatch?.[1] && fenceMatch[1][0] === fence[0] && fenceMatch[1].length >= fence.length) fence = undefined;
			body.push(line);
			continue;
		}
		if (fenceMatch?.[1]) {
			closeParagraph();
			fence = fenceMatch[1];
			body.push(line);
			continue;
		}
		if (page.drop?.test(line)) continue;
		const h1 = !title ? line.match(/^#\s+(.+?)\s*#*\s*$/) : null;
		if (h1?.[1]) {
			title = plainText(h1[1]);
			continue;
		}

		if (line.trim() === '') {
			closeParagraph();
			otherBlock = false;
		} else if (/^\s{0,3}(#|>|[-*+]\s|\d+[.)]\s|<|\||!\[)/.test(line)) {
			closeParagraph();
			otherBlock = true;
		} else if (!otherBlock && !(paragraph.length === 0 && /^\s/.test(line))) {
			paragraph.push(line);
		}

		body.push(await rewriteLine(page.source, line));
	}
	closeParagraph();

	if (!title) throw new Error(`${page.source}: no top-level "# " heading to use as the page title`);
	while (body[0]?.trim() === '') body.shift();

	const frontmatter = [
		'---',
		`title: ${JSON.stringify(title)}`,
		...(description ? [`description: ${JSON.stringify(description)}`] : []),
		`editUrl: ${JSON.stringify(`${REPO_URL}/edit/main/${page.source}`)}`,
		'sidebar:',
		`  order: ${page.order}`,
		...(page.label ? [`  label: ${JSON.stringify(page.label)}`] : []),
		'---',
		'',
		`<!-- Generated from ${page.source} by site/scripts/sync-docs.ts. Edit the source file, not this copy. -->`,
		'',
		'',
	];
	return `${frontmatter.join('\n')}${body.join('\n').replace(/\n*$/, '\n')}`;
}

async function main() {
	const missing: string[] = [];
	for (const page of PAGES) {
		if (!(await Bun.file(join(REPO_DIR, page.source)).exists())) missing.push(page.source);
	}
	if (missing.length > 0) throw new Error(`missing source file(s):\n  ${missing.join('\n  ')}`);

	// Clear previous output, keeping committed hand-authored pages.
	await rm(ASSETS_OUT_DIR, { recursive: true, force: true });
	const existing = await readdir(CONTENT_DIR).catch(() => [] as string[]);
	await Promise.all(
		existing
			.filter((entry) => entry !== COMMITTED_ENTRY)
			.map((entry) => rm(join(CONTENT_DIR, entry), { recursive: true, force: true })),
	);

	for (const pattern of ALWAYS_COPIED_ASSETS) {
		for await (const sub of new Bun.Glob(pattern).scan({ cwd: join(REPO_DIR, 'assets') })) {
			await copyAsset(`assets/${sub}`);
		}
	}

	for (const page of PAGES) {
		const outPath = join(CONTENT_DIR, page.target);
		await Bun.write(outPath, await convert(page));
		console.log(`synced ${page.source} -> ${posix.join('src/content/docs/docs', page.target)} (${routeFor(page.target)})`);
	}
	console.log(`copied ${copiedAssets.size} asset(s) into public/assets/`);
	if (unmapped.length > 0) {
		console.warn(`links that could not be mapped to a site page or existing repository path:\n  ${unmapped.join('\n  ')}`);
	}
}

try {
	await main();
} catch (error) {
	console.error(`sync-docs: ${error instanceof Error ? error.message : String(error)}`);
	process.exit(1);
}
