apiVersion: flareway.bhyoo.com/v1alpha1
kind: DeviceSettings
metadata:
  name: default
  namespace: flareway-system
spec:
  accountRef:
    name: example-account
  gatewayProxyEnabled: true
  gatewayUdpProxyEnabled: true
  rootCertificateInstallationEnabled: true
  useZtVirtualIp: true
  managementPolicy: ObserveOnly
  deletionPolicy: Orphan
