apiVersion: flareway.bhyoo.com/v1alpha1
kind: GatewayClassConfig
metadata:
  name: default
spec:
  accountRef:
    name: example-account
  connector:
    image: cloudflare/cloudflared:2026.10.0@sha256:9b49eed8f62806d5d45ddf59ecefb5710429598ea6d3fcccd2af938f621b2b07
    replicas: 2
    protocol: Auto
    gracePeriod: 60s
  proxy:
    image: envoyproxy/envoy:distroless-v1.39.2
    streamIdleTimeout: 1h
    concurrency: 1
  privateDNS:
    image: coredns/coredns:1.14.7@sha256:7efd3c635b03efd68c4e8398fc45f0d993d0e9ab016f72c1cefb0fd6d01aa286
  dns:
    mode: Managed
  originJWT:
    mode: Required
  conformanceMode: false
  conformance:
    serviceType: LoadBalancer
