//go:build e2e

/*
Copyright 2026 Byeonghoon Yoo.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package e2e

import (
	"context"
	"errors"
	"fmt"
	"time"

	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/client-go/discovery"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/isac322/flareway/internal/dataplane"
	"github.com/isac322/flareway/test/e2e/internal/cleanup"
	"github.com/isac322/flareway/test/e2e/internal/poll"
)

// teardownTierTimeout bounds each namespaced drain stage. Tunnel finalizers
// get the largest budget because remote tunnel and DNS teardown is the
// slowest stage and must finish while the account credentials still exist.
const (
	teardownTierTimeout   = 3 * time.Minute
	teardownTunnelTimeout = 5 * time.Minute
	teardownNSTimeout     = 5 * time.Minute
	teardownClusterBudget = 2 * time.Minute
	// teardownJanitorTimeout bounds the remote sweep that runs after all
	// Kubernetes teardown has converged.
	teardownJanitorTimeout = 5 * time.Minute
)

// Platform HostnameRoutes are generated by the Gateway controller into the
// operator namespace for private listeners; these labels select the ones
// generated for this run. Keys mirror generatedPlatformObjectLabel and
// generatedSourceNamespaceLabel in internal/controller.
const (
	platformObjectLabel   = "flareway.bhyoo.com/platform-object"
	sourceNamespaceLabel  = "flareway.bhyoo.com/source-namespace"
	platformRouteKind     = "HostnameRoute"
	platformRouteDrainMax = 3 * time.Minute
)

// teardownNodeTimeout is the AfterSuite budget: every stage timeout plus a
// margin for discovery, deletes, and reporting.
const teardownNodeTimeout = time.Duration(cleanup.TierCount-1)*teardownTierTimeout +
	platformRouteDrainMax + teardownTunnelTimeout + teardownNSTimeout +
	teardownClusterBudget + teardownJanitorTimeout + 2*time.Minute

// teardownSuite removes the run's resources in reverse dependency order. It
// never issues the Namespace deletion while a namespaced Flareway or Gateway
// API object remains: the CloudflareAccount credential Secret lives in that
// namespace and tunnel finalizers fail closed without it.
func teardownSuite(ctx context.Context) error {
	lists, err := kubeClientset.Discovery().ServerPreferredResources()
	if err != nil {
		var groupErr *discovery.ErrGroupDiscoveryFailed
		if !errors.As(err, &groupErr) || discoveryFailedForRelevantGroups(groupErr) {
			return fmt.Errorf("discover resources for teardown: %w", err)
		}
	}
	plan, err := cleanup.PlanTeardown(lists)
	if err != nil {
		return err
	}

	// A failed stage aborts all later Kubernetes teardown: continuing would
	// delete the credential Secret or the CloudflareAccount while dependents
	// still need them, recreating the CredentialsUnavailable wedge.
	for tier, resources := range plan.Tiers {
		timeout := teardownTierTimeout
		if cleanup.Tier(tier) == cleanup.TierTunnels {
			// Generated platform HostnameRoutes in the operator namespace
			// reference this run's tunnels; they must drain before the
			// tunnel tier or tunnel finalizers stay blocked.
			if err := drainPlatformHostnameRoutes(ctx, plan); err != nil {
				return fmt.Errorf("drain platform hostname routes: %w", err)
			}
			timeout = teardownTunnelTimeout
		}
		if err := drainTier(ctx, resources, timeout); err != nil {
			return fmt.Errorf("drain %s tier: %w", cleanup.Tier(tier), err)
		}
	}

	// Only now is it safe to delete the namespace: every namespaced
	// finalizer has completed, so removing the credential Secret cannot
	// wedge a dependent.
	ns := &corev1.Namespace{ObjectMeta: metav1.ObjectMeta{Name: namespace}}
	if err := deleteAndWait(ctx, ns, teardownNSTimeout); err != nil {
		return fmt.Errorf("delete namespace %s: %w", namespace, err)
	}

	// Cluster-scoped fixtures go last; the CloudflareAccount must outlive
	// every namespaced dependent that resolves it during cleanup.
	clusterCtx, cancel := context.WithTimeout(ctx, teardownClusterBudget)
	defer cancel()
	for _, fixture := range []client.Object{
		object("gateway.networking.k8s.io/v1", "GatewayClass", "", className, nil),
		object("flareway.bhyoo.com/v1alpha1", "GatewayClassConfig", "", classConfig, nil),
		object("flareway.bhyoo.com/v1alpha1", "CloudflareAccount", "", accountName, nil),
	} {
		if err := deleteAndWait(clusterCtx, fixture, 0); err != nil {
			return fmt.Errorf("delete cluster fixture: %w", err)
		}
	}

	return nil
}

func discoveryFailedForRelevantGroups(groupErr *discovery.ErrGroupDiscoveryFailed) bool {
	for gv := range groupErr.Groups {
		if cleanup.RelevantGroup(gv.Group) {
			return true
		}
	}
	return false
}

// drainTier deletes every namespaced object of each resource in the tier,
// then waits for the whole tier to be empty under one shared deadline so
// finalizers finish before the next dependency stage begins. Any list or
// delete error aborts the tier immediately.
func drainTier(ctx context.Context, resources []cleanup.Resource, timeout time.Duration) error {
	tierCtx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()

	for _, resource := range resources {
		items, err := listNamespaced(tierCtx, resource, namespace)
		if err != nil {
			return err
		}
		for i := range items.Items {
			item := &items.Items[i]
			if err := kubeClient.Delete(tierCtx, item); err != nil && !apierrors.IsNotFound(err) {
				return fmt.Errorf("delete %s %s/%s: %w",
					resource.Kind, item.GetNamespace(), item.GetName(), err)
			}
		}
	}

	_, err := poll.Until(tierCtx, 2*time.Second, func(checkCtx context.Context) (bool, error) {
		for _, resource := range resources {
			items, err := listNamespaced(checkCtx, resource, namespace)
			if err != nil {
				return false, err
			}
			if len(items.Items) != 0 {
				return false, nil
			}
		}
		return true, nil
	})
	return err
}

func listNamespaced(ctx context.Context, resource cleanup.Resource, ns string, opts ...client.ListOption) (*unstructured.UnstructuredList, error) {
	items := &unstructured.UnstructuredList{}
	items.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   resource.Group,
		Version: resource.Version,
		Kind:    resource.Kind + "List",
	})
	opts = append([]client.ListOption{client.InNamespace(ns)}, opts...)
	if err := kubeClient.List(ctx, items, opts...); err != nil {
		return nil, fmt.Errorf("list %s in namespace %s: %w", resource.Kind, ns, err)
	}
	return items, nil
}

// drainPlatformHostnameRoutes removes the HostnameRoutes the Gateway
// controller generated into the operator namespace for this run's private
// listeners. They reference the run's tunnels, so they must finish before
// the tunnel tier drains.
func drainPlatformHostnameRoutes(ctx context.Context, plan cleanup.Plan) error {
	var route cleanup.Resource
	found := false
	for _, resource := range plan.Tiers[cleanup.TierRoutesAndGateways] {
		if resource.Kind == platformRouteKind {
			route = resource
			found = true
		}
	}
	if !found {
		return fmt.Errorf("%s not discovered; cannot drain generated platform routes", platformRouteKind)
	}

	stageCtx, cancel := context.WithTimeout(ctx, platformRouteDrainMax)
	defer cancel()
	selector := client.MatchingLabels{
		platformObjectLabel:  "true",
		sourceNamespaceLabel: namespace,
	}
	items, err := listNamespaced(stageCtx, route, dataplane.DefaultOperatorNamespace, selector)
	if err != nil {
		return err
	}
	for i := range items.Items {
		item := &items.Items[i]
		if err := kubeClient.Delete(stageCtx, item); err != nil && !apierrors.IsNotFound(err) {
			return fmt.Errorf("delete platform %s %s/%s: %w",
				platformRouteKind, item.GetNamespace(), item.GetName(), err)
		}
	}
	_, err = poll.Until(stageCtx, 2*time.Second, func(checkCtx context.Context) (bool, error) {
		remaining, err := listNamespaced(checkCtx, route, dataplane.DefaultOperatorNamespace, selector)
		if err != nil {
			return false, err
		}
		return len(remaining.Items) == 0, nil
	})
	return err
}

// deleteAndWait issues a delete and blocks until the object, including its
// finalizers, is fully removed. A zero timeout reuses ctx's deadline.
func deleteAndWait(ctx context.Context, value client.Object, timeout time.Duration) error {
	waitCtx := ctx
	cancel := func() {}
	if timeout > 0 {
		waitCtx, cancel = context.WithTimeout(ctx, timeout)
	}
	defer cancel()

	kind := value.GetObjectKind().GroupVersionKind().Kind
	if kind == "" {
		kind = fmt.Sprintf("%T", value)
	}
	if err := kubeClient.Delete(waitCtx, value); err != nil && !apierrors.IsNotFound(err) {
		return fmt.Errorf("delete %s %s: %w", kind, client.ObjectKeyFromObject(value), err)
	}
	_, err := poll.Until(waitCtx, 2*time.Second, func(checkCtx context.Context) (bool, error) {
		current := value.DeepCopyObject().(client.Object)
		getErr := kubeClient.Get(checkCtx, client.ObjectKeyFromObject(value), current)
		return apierrors.IsNotFound(getErr), client.IgnoreNotFound(getErr)
	})
	if err != nil {
		return fmt.Errorf("wait for %s %s deletion: %w", kind, client.ObjectKeyFromObject(value), err)
	}
	return nil
}
